###  [2021-01-26-20:33] CG

version: '3.5'
services:

  rstudio0:
    build: ./rstudio
    restart: always
    image: rstudio_nodenet
    container_name: rstudio0
    hostname: rstudio0
    environment:
      - PASSWORD=rstudiojh
    ports:
      - "8787:8787"     # RStudio UI
      - "4040:4040"     # Spark Web UI
    volumes:
      - rstudio_data_0:/home/rstudio
    networks:
      - nodeNetwork

  rstudio1:
    build: ./rstudio
    restart: always
    image: rstudio_nodenet
    container_name: rstudio1
    hostname: rstudio1
    environment:
      - PASSWORD=rstudiojh
    ports:
      - "8788:8787"     # RStudio UI
      - "4041:4040"     # Spark Web UI
    volumes:
      - rstudio_data_1:/home/rstudio
    networks:
      - nodeNetwork

  nodeRED:
    build: ./nodeRED
    restart: always
    image: node_red_local
    container_name: nodeRED
    hostname: nodeRED
    ports:
      - "1880:1880"     # NodeRED UI
    volumes:
      - nodeRED_data:/data
    networks:
      - nodeNetwork

volumes:
  rstudio_data_0:
  rstudio_data_1:
  nodeRED_data:

networks:
  nodeNetwork:
    driver: bridge
